# Welcome to Jekyll them with Webstorm!!

# Site settings
# These are used to personalize your new site. If you look in the HTML files,

title: jekyll theme with webstorm
email: your-email@example.com
username: ebool # input your name
description: >- # this means to ignore newlines until "baseurl:"
  jekyll theme with webstorm
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# If you ar e using Sass @import statements

collections:
  authors:
    output: true

sass:
  sass_dir: _sass

# Build settings

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

